name: Sync to Hugging Face Hub

# This tells GitHub to run this script every time you push to the 'main' branch
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      
      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        # This forces your GitHub code into your Hugging Face Space
        run: git push --force https://Abhishek1205:$HF_TOKEN@huggingface.co/spaces/Abhishek1205/Email-RL-Agent main